// "use client"; // Using Client
import React from 'react';
import { Providers } from "./providers";

import Navigation from '../components/Navigation';

import './globals.css';
import { Inter, Poppins } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: "400" });




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Providers>
          <Navigation/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
